/**
 * Kathir OS — Agents Worker (cron only)
 *
 * Triggers (see wrangler.toml):
 *   */15 * * * *  GitHub + HF sync
 *   0   * * * *  Status sync (light GitHub refresh)
 *   0   6 * * *  Daily digest (yesterday's activity → log entry)
 *   0   7 * * *  Paper monitor (arXiv → top 3 via LLM)
 *
 * Env bindings:
 *   R2, GITHUB_TOKEN, GH_USERNAME, HF_USERNAME,
 *   LLM_PROVIDER + provider key (GEMINI_KEY / OPENAI_KEY / ANTHROPIC_KEY)
 */

import { chat } from "../lib/llm.js";
import { mergedActivity, refreshGitHub, refreshHuggingFace } from "../lib/refresh.js";

const ARXIV_QUERIES = [
  "mechanistic interpretability transformer",
  "sparse autoencoders features superposition",
  "Hindi language model pretraining",
  "federated learning language model",
  "JAX TPU distributed training",
];

export default {
  async scheduled(event, env, ctx) {
    const cron = event.cron;
    console.log(`[agent] cron: ${cron}`);

    switch (cron) {
      case "0 6 * * *":
        await runDigestAgent(env);
        break;
      case "0 7 * * *":
        await runPaperMonitor(env);
        break;
      case "0 * * * *":
        await refreshGitHub(env);
        break;
      case "*/15 * * * *":
        await Promise.all([refreshGitHub(env), refreshHuggingFace(env)]);
        break;
      default:
        await Promise.all([refreshGitHub(env), refreshHuggingFace(env), runPaperMonitor(env)]);
    }
  },
};

// ── Digest Agent ──────────────────────────────────────────────
async function runDigestAgent(env) {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const dateStr = yesterday.toISOString().slice(0, 10);

  if (await env.R2.get(`logs/${dateStr}.md`)) {
    console.log(`[digest] manual log exists for ${dateStr}, skipping`);
    return;
  }

  const allActivity = await mergedActivity(env);
  const dayActivity = allActivity.filter(item => {
    try { return new Date(item.ts).toISOString().slice(0, 10) === dateStr; }
    catch { return false; }
  });

  if (dayActivity.length === 0) {
    const content = `# ${dateStr}\n\n_Quiet day — no recorded activity._\n`;
    await env.R2.put(`logs/digest-${dateStr}.md`, content, {
      httpMetadata: { contentType: "text/markdown" },
    });
    return;
  }

  const summary = dayActivity
    .map(a => `- [${a.source}] ${a.message} (${a.repo || ""})`)
    .join("\n");

  const prompt = `You are writing a daily dev log entry for Kathir K S's personal portfolio.
Write a concise, honest, first-person log entry (3-5 sentences) summarizing this activity.
Sound like a researcher's notebook — direct, no fluff, slightly informal.
Start directly with what happened, no preamble like "Today I...".

Activity on ${dateStr}:
${summary}

Write the log entry now:`;

  let digest;
  try {
    const r = await chat(env, {
      messages: [{ role: "user", content: prompt }],
      maxTokens: 300,
      temperature: 0.5,
    });
    digest = r.text;
  } catch (e) {
    console.error("[digest] LLM error:", e);
    return;
  }
  if (!digest) return;

  const content = `# ${dateStr}\n\n${digest}\n\n---\n_Auto-generated by digest agent from GitHub activity._\n`;
  await env.R2.put(`logs/digest-${dateStr}.md`, content, {
    httpMetadata: { contentType: "text/markdown" },
  });
  console.log(`[digest] wrote digest for ${dateStr}`);
}

// ── Paper Monitor ─────────────────────────────────────────────
async function runPaperMonitor(env) {
  const allPapers = [];

  for (const query of ARXIV_QUERIES) {
    try {
      const res = await fetch(
        `https://export.arxiv.org/api/query?search_query=all:${encodeURIComponent(query)}&sortBy=submittedDate&sortOrder=descending&max_results=5`,
        { headers: { "User-Agent": "kathir-os-agent/1.0" } }
      );
      if (!res.ok) continue;
      allPapers.push(...parseArxivXML(await res.text()));
    } catch (e) {
      console.error(`[papers] query "${query}" failed:`, e);
    }
  }

  const seen = new Set();
  const unique = allPapers.filter(p => seen.has(p.id) ? false : (seen.add(p.id), true));
  if (unique.length === 0) return;

  const paperList = unique.slice(0, 15)
    .map((p, i) => `${i + 1}. "${p.title}" — ${p.summary.slice(0, 150)}... [${p.id}]`)
    .join("\n\n");

  const prompt = `Kathir K S is an AI researcher focused on: mechanistic interpretability, sparse autoencoders,
Hindi language models, federated learning, JAX/TPU infrastructure, and ARC-AGI.

From this list of recent arXiv papers, pick the 3 most relevant to his work and explain
in one sentence each why it matters to him. Return ONLY valid JSON array, no other text:
[{"id":"...","title":"...","why":"...","url":"..."},...]

Papers:
${paperList}`;

  let raw;
  try {
    const r = await chat(env, {
      messages: [{ role: "user", content: prompt }],
      maxTokens: 500,
      temperature: 0.5,
    });
    raw = r.text;
  } catch (e) {
    console.error("[papers] LLM error:", e);
    return;
  }

  let picks;
  try {
    const cleaned = raw.replace(/```json\n?|\n?```/g, "").trim();
    picks = JSON.parse(cleaned);
    if (!Array.isArray(picks)) throw new Error("not an array");
  } catch (e) {
    console.error("[papers] failed to parse LLM JSON; falling back to top 3");
    picks = unique.slice(0, 3).map(p => ({
      id: p.id,
      title: p.title,
      why: "Relevant to current research focus.",
      url: p.url,
    }));
  }

  const enriched = picks.map(pick => {
    const original = unique.find(p => p.id === pick.id) || {};
    return {
      id: pick.id,
      title: pick.title || original.title,
      why: pick.why,
      url: pick.url || original.url,
      authors: original.authors || [],
      published: original.published || null,
    };
  });

  await env.R2.put("feed/papers.json", JSON.stringify(enriched), {
    httpMetadata: { contentType: "application/json" },
  });
  console.log(`[papers] saved ${enriched.length} picks`);
}

// ── arXiv XML parser (regex — fragile but stable for arXiv's format) ──
function parseArxivXML(xml) {
  const papers = [];
  const entries = xml.split("<entry>").slice(1);
  for (const entry of entries) {
    const id = (entry.match(/<id>([^<]+)<\/id>/) || [])[1] || "";
    const title = (entry.match(/<title>([^<]+)<\/title>/) || [])[1] || "";
    const summary = (entry.match(/<summary>([^<]+)<\/summary>/) || [])[1] || "";
    const published = (entry.match(/<published>([^<]+)<\/published>/) || [])[1] || "";
    const authorMatches = [...entry.matchAll(/<name>([^<]+)<\/name>/g)];
    const authors = authorMatches.slice(0, 3).map(m => m[1]);
    const arxivId = id.split("/abs/").pop() || id;
    papers.push({
      id: arxivId,
      title: title.trim().replace(/\s+/g, " "),
      summary: summary.trim().replace(/\s+/g, " "),
      authors,
      published,
      url: `https://arxiv.org/abs/${arxivId}`,
    });
  }
  return papers;
}
